STRIPE_PUBLISHABLE_KEY:	pk_test_51GroxnGYhSS9s9rvN6vCJC23mTemFWoKTIXA0ztQ1QJswzi29Qf95PFb9nG6AKjwijEKb4fqvL2MkPeOoCn2s5zY00RAV6TboP
STRIPE_SECRET_KEY_DEV: 	sk_test_51GroxnGYhSS9s9rvxCNA415dtnmJuhqZiTjaC0OWkB5QwSXDZas33I1JSpK5W7PBVRhzS1JT9VwWTnanTpbfj90N00evTEaKgI
ADMIN_EMAIL: jenniferruditsky@gmail.com
ADMIN_PASSWORD: Ponyboy3
SAM_PASSWORD: Nellie123

